plugin: aws_ec2

#aws_access_key: AKIAVE44ROPXKNFDUG6E
#aws_secret_key: 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

regions:
  - ap-southeast-2

filters:
  instance-state-name : running
 
keyed_groups:
  - key: tags.Name
    prefix: ""
    separator: ""

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address
